version: 2.1

workflows:
  hourly-build:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: master
    jobs:
      - buildCron
  main:
    jobs:
      - buildSingle

jobs:
  buildSingle:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: echo "Hi"
  buildCron:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Make sure Dockerfile Builds"
          command: |
            echo $DATE >> fake-log.txt
            git config user.name "Ricardo"
            git config user.email "FelicianoTech@gmail.com"
            git add fake-log.txt
            git commit -m "Add to fake log."
            git push
