version: 2.1

workflows:
  hourly-build:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Make sure Dockerfile Builds"
          command: docker build -t test/testing:dev .
